### ISSUE TITLE
Custom Modal not showing up when prop modalComponentHandler is passed

### ISSUE THREAD

**Issue by dsaw** [dioscarey/react-beforeunload-component#2]
I am able to get the `leave changes` modal working and it pops up when I try to close/refresh my popup window. I passed in a custom component in `modalComponentHandler` but the default alert is still coming. Is this usage correct [from this article](https://medium.com/@dioscarey/react-beforeunload-component-c7198f955ee),  am I missing something here?
![modalcallbackcode](https://user-images.githubusercontent.com/5353891/107518853-80eaa700-6bd5-11eb-9e86-6b49b44a20a4.PNG)
Heres the the simplified component code ->
```
const UnsavedChangesModal = ({showUnsavedModalCallback }) => {
    const hideModal = () => {
        showUnsavedModalCallback(false);
    };

    return (
        <Modal id='prompt' size='small'>
            <ModalHeader
                id='prompt-header'
                title={meta.localeBundle['navigateAwayUnsavedChanges_header_label']}
                closeButton={true}
                onClose={hideModal}
            />
            <ModalBody id='prompt-body'>{meta.localeBundle['navigateAway_message']}</ModalBody>
            <ModalFooter id='prompt-footer'><Button
                id='ok-button'
                type='primary'
                onClick={hideModal}>
                {meta.localeBundle['ok_button_label']}
            </Button></ModalFooter>
        </Modal>
    );
}
```

Thanks for the component btw.

**Comment by dsaw** [comment]
On checking the docs, it seems customizing the modal other than the text seems to be difficult. Browser show their own alert popups by default.
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

**Comment by dioscarey** [comment]
@dsaw Sorry for the late reply, ya, it's not possible to replace the browser alert. **react-beforeunload-component** package is a combination of both, it prevents **React router** with a custom alert and prevents **browser Go back or reload the page**, **this last one cannot be customized.**

**Comment by dsaw** [comment]
Right, I used the default modal anyways since its not good practice.
