### ISSUE TITLE
Custom modal not showing

### ISSUE THREAD

**Issue by chrispalka** [dioscarey/react-beforeunload-component#4]
Hi! Thank you for creating this package, looking forward to using it.

I am however having trouble displaying my custom modal, and instead just displays the normal browser default alert

What I have so far:

![image](https://user-images.githubusercontent.com/26169911/129409471-89976a78-7a07-4f2b-b146-a39f5b405589.png)

**Comment by orendon123** [comment]
When you reload the site or want to go back to history you will see the default alert, but if you click inside your site (out of the compoent) will be displayed the custom modal. There's no way to customize the browser modal.
